name: store_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/general-sans/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/general-sans/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/general-sans/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/general-sans/GeneralSans-Bold.otf
          weight: 700
