name: store_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  speech_to_text: ^7.0.0
  lottie: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter  
  provider: ^6.1.4
  pinput: ^5.0.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  permission_handler: ^11.4.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_switch: ^0.3.2
  birth_picker: ^1.1.2+1
  intl_phone_field: ^3.2.0
  connectivity_plus: ^6.1.4
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  dev: ^1.0.0
  build_runner: ^2.4.15
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  hive: ^2.2.3
  cached_network_image: ^3.4.1
  credit_card_type_detector: ^3.0.0
  flutter_credit_card: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animation.json
    - assets/tick_animation.json
  fonts:
    - family: GeneralSans
      fonts:
        - asset: fonts/GeneralSans/GeneralSans-Regular.otf
          weight: 400
        - asset: fonts/GeneralSans/GeneralSans-Medium.otf
          weight: 500
        - asset: fonts/GeneralSans/GeneralSans-SemiBold.otf
          weight: 600
        - asset: fonts/GeneralSans/GeneralSans-Bold.otf
          weight: 700
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
