// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJbfn-GMwMVLj6oKCrQFGDn8__w72s3gI',
    appId: '1:75442654875:web:c3fa01b1aac79187a6803e',
    messagingSenderId: '75442654875',
    projectId: 'storeapp-102bc',
    authDomain: 'storeapp-102bc.firebaseapp.com',
    storageBucket: 'storeapp-102bc.firebasestorage.app',
    measurementId: 'G-8KDNP0RYRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2DuOZwxQCKoT6_q0-CFS92DdSUT4_jM',
    appId: '1:75442654875:android:cffa4d61b03017b5a6803e',
    messagingSenderId: '75442654875',
    projectId: 'storeapp-102bc',
    storageBucket: 'storeapp-102bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3tpqtan2usljE8sBNnjgpEBxUY8zVgWs',
    appId: '1:75442654875:ios:219ca695c8e64042a6803e',
    messagingSenderId: '75442654875',
    projectId: 'storeapp-102bc',
    storageBucket: 'storeapp-102bc.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );
}
