// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE-iCL8YimRAVrUrSw_DVieC9Z1XKvNtU',
    appId: '1:667067499966:web:e055cf19df97635217a5ef',
    messagingSenderId: '667067499966',
    projectId: 'store-app-862a6',
    authDomain: 'store-app-862a6.firebaseapp.com',
    storageBucket: 'store-app-862a6.firebasestorage.app',
    measurementId: 'G-ZB7XSM1QV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQi0ORN9j6hxc6siyRHSPwkuW5Ae8W9Lw',
    appId: '1:667067499966:android:2e4f79b2a23e64e317a5ef',
    messagingSenderId: '667067499966',
    projectId: 'store-app-862a6',
    storageBucket: 'store-app-862a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANqjuHJEFN1xnJbfcaywSpsuNfM5Af-00',
    appId: '1:667067499966:ios:40ea4f825736a63817a5ef',
    messagingSenderId: '667067499966',
    projectId: 'store-app-862a6',
    storageBucket: 'store-app-862a6.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );
}
